---
abstract: 'a distro that always fails the `make test` stage'
author:
  - 'Martin Thurn c<mthurn@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Devel::Fail::MakeTest
name: Devel-Fail-MakeTest
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
version: 1.013
